### ISSUE TITLE
Missing Quantity for Intensity

### ISSUE THREAD

**Issue by htreu** [unitsofmeasurement/si-units#40]
Intensity is defined as the power transferred per unit area. In the SI system, it has units watts per square metre (W/m2).
See https://en.wikipedia.org/wiki/Intensity_(physics).

Currently javax.measure.quantity does also not define Intensity.
May this be added to uom si-units?

**Comment by keilw** [comment]
Yes, after https://github.com/unitsofmeasurement/si-units/tree/master/quantity (not the API, we would rarely add new quantities there, only a small number should for size reasons) would get the Quantity type first, sure. Wikipedia refers to the **SI system**, so happy to add it here.

**Comment by keilw** [comment]
As mentioned, before we can merge a PR here, please sign the [ECA](https://www.eclipse.org/legal/ECA.php). Working for Deutsche Telekom you probably best qualify for a corporate rep, ask @kaikreuzer from SmartHome about it. If you do not use or contribute this on behalf of Deutsche Telekom, then you may also sign an Individual ECA, we just require this here for Eclipse projects like SmartHome, EE4J or a whole lot of IoT projects to use those quantities without problems. Thanks.

**Comment by keilw** [comment]
Hi @htreu Thanks for the update. Great, then we're good to go. As the milestone https://github.com/unitsofmeasurement/si-units/milestone/9 shows, SI Units will play an even bigger role also when it comes to documentation and presentation till early 2019 because of the SI redefinition, so we are happy about contributors and committers here as in the JSR itself. Should you or someone else wish to represent Deutsche Telekom in the JSR 385 EG, please let us know, or nominate yourself via https://jcp.org/en/jsr/egnom?id=385. Based on the help by @kaikreuzer and SmartHome we would not hesitate to accept it.
