### ISSUE TITLE
Port UOM NonSI Units 

### ISSUE THREAD

**Issue by forbode** [unitsofmeasurement/si-units#47]
As it stands there are a number of NonSI units, such as Decibel, in the UOM NonSI (private) package. As such they are unusable, but exist. Why not port them to the si-units NonSI?

https://github.com/unitsofmeasurement/uom-systems/blob/0.7.2/common-java8/src/main/java/systems/uom/common/NonSI.java

- [x] [Table 6](https://www.bipm.org/en/publications/si-brochure/table6.html)
- [ ] [Table 7](https://www.bipm.org/en/publications/si-brochure/table7.html)
- [x] [Table 8](https://www.bipm.org/en/publications/si-brochure/table8.html)
- [x] [Table 9](https://www.bipm.org/en/publications/si-brochure/table9.html)

**Comment by keilw** [comment]
This NonSI was a chimera and is meant to go away. Everything in the systems modules is "Non-SI" which is why the class was relocated to [si-units](https://github.com/unitsofmeasurement/si-units) Based on units from https://www.bipm.org/en/publications/si-brochure/chapter4.html. I saw BEL and DECIBEL are also there, which is why we may have to consider introducing [Level](https://github.com/unitsofmeasurement/uom-systems/blob/master/quantity/src/main/java/systems/uom/quantity/Level.java) to si-quantity.
