### ISSUE TITLE
New NonSi - RPM

### ISSUE THREAD

**Issue by ChristianLutz** [unitsofmeasurement/si-units#75]
Hello,

I don't know if this is a valid request. Could we add RPM 
https://en.wikipedia.org/wiki/Revolutions_per_minute

`
protected static final Unit<Frequency> REVOLUTIONS_PER_MINUTE = addUnit(AbstractUnit.ONE.divide(MINUTE)).asType(Frequency.class);
`

I know it is similar to FRAMES_PER_SECOND and HERTZ, but it is used in a different context.

regards
Christian

**Comment by keilw** [comment]
I'm afraid we have to be a little more restrictive here and since most of the NonSI units that are not listed in Table 8 of the [SI Brochure](https://www.bipm.org/utils/common/pdf/si-brochure/SI-Brochure-9-EN.pdf) but found elsewhere either in the `CGS` or `USCustomary` systems, I will transfer this ticket to UOM Systems.

**Comment by keilw** [comment]
Created https://github.com/unitsofmeasurement/uom-systems/issues/183
