### ISSUE TITLE
Mixup between Units and Constants

### ISSUE THREAD

**Issue by jensgw** [unitsofmeasurement/si-units#84]
Hi there, I am wondering why natural constants are formally handeled as NonSI Unit. Semantically that seems wrong. A constant is not a unit.

**Comment by keilw** [comment]
They are constants, we have other constants like `ONE` so there is no big difference here.

**Comment by jensgw** [comment]
I don't get it. Please elaborate.

A physical constant is defined as a number value with a corersponging unit, e.g. speed of light c = 299792458 m/s. Precisely not a unit itself. However you treat it as a unit.

What is the purpose of let's say defining a a variable "s" in units of speed of light?

If you mean natural units all number values of your constants are wrong, e.g. speed of light in natural units is 1 per definition.

**Comment by keilw** [comment]
Where those constants have a distinct quantity they are used, c is the `Speed` as you say in m/s therefore the quantity is used, in other cases the constants are `Dimensionless`, while e.g. the Planck Constant is also said to be of type [Action](https://en.wikipedia.org/wiki/Action_(physics)).

**Comment by desruisseaux** [comment]
Do you have a link to javadoc or source code where those constants are defined? Just curious to see how they are defined. I would expect something like below, is it the case?

```java
Quantity<Speed> SPEED_OF_LIGHT = QuantityFactory.create(299792458, Units.METER_PER_SECOND);
```

I.e. a constant of type `Quantity` (not `Unit`).

**Comment by keilw** [comment]
It's all in [SI](https://github.com/unitsofmeasurement/si-units/blob/master/units/src/main/java/si/uom/SI.java).
All constants are defined as units of a particular quantity, Some, at least the Speed of Light have been there like that ever since JSR 275, see what previously was declared under [NonSI](https://javadoc.io/doc/org.jscience/jscience/latest/javax/measure/unit/NonSI.html).
"A unit of velocity relative to the speed of light (standard name c)." according to the JavaDoc back then.
